---
# ------------------------------------------------------------------------
# tasks file for deployment_user
# ------------------------------------------------------------------------

- name: check for sudo and admin groups
  group: name="{{ item }}" state=present system=yes
  with_items:
    - "{{ deployment_user_grps }}"

- name: check for deploy user
  user:
    name: "{{ deployment_user_name }}"
    comment: "deploy"
    # groups: "sudo,admins" TODO
    # password: "{{ srv_init_deploy_user.password }}" TODO
    shell: "/bin/bash"
    state: present

- name: copy ssh user config
  copy:
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
    src: ssh_config
    dest: "~{{ item }}/.ssh/config"
  with_items:
    - "{{ deployment_user_name }}"

# AllowUsers {% for u in ssh_server_users %}{{ u.name }} {% endfor %}

- name: configure sudoers file
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    owner: "root"
    group: "root"
    mode: "0440"

- name: deploy ssh public keys for ssh users
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.pubkey }}"
    state: "{{ item.state | default("absent") }}"
  with_items:
    - "{{ ssh_server_users }}"
