---
# ------------------------------------------------------------------------
# handlers file for deployment_user
# ------------------------------------------------------------------------

- name: restart ssh server
  service:
    name: "{{ ssh_server_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
